#!/usr/bin/env bash
# Fixes Nginx configuration to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
