#!/usr/bin/env bash
# Configures Nginx with a 301 redirect and a custom 404 error page

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    
    server_name _;
    
    # Tell Nginx to use our custom 404 page
    error_page 404 /404.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
EOF

service nginx restart
